##############################
# Netlify configuration file #
##############################

# List of Build plugins
[[plugins]]
# Use the current plugin in builds for testing and debugging.
# Local path to the plugin.
package = "."

  # Plugin configuration Sample
    [plugins.inputs]
    #urls = "https://www.example1.com, https://www.example2.com"
    #location = "Dulles:Chrome"
    #connectivity = "3G"
    #firstViewOnly = "true"
    #runs = "1"
    #emulateMobile = "true"
    #block = "https://www.adblock.com"
    #lighthouse = "true"
    #throttleCPU = "10"
    #specs = '{"average": {"firstView": {"chromeUserTiming.CumulativeLayoutShift": 0.1,"chromeUserTiming.LargestContentfulPaint": 2500,"firstContentfulPaint": 2000,"TotalBlockingTime": 0.1}}}'


 