##############################
# Netlify configuration file #
##############################

# List of Build plugins
[[plugins]]
# Use the current plugin in builds for testing and debugging.
# Local path to the plugin.
package = "."

  # Plugin configuration
    [plugins.inputs.options]
    location = "Dulles:Chrome"
    connectivity = "3G"
    firstViewOnly = "true"
    runs = "1"
    emulateMobile = "true"
    block = "https://www.adblock.com"
    lighthouse = "true"
    throttleCPU = "10"


[build]
# Dummy build command
command = "echo onBuild"

[build.environment]
NODE_VERSION = "12.20.0"

 